In [12]:
import json as j
import pandas as pd
import re
import numpy
import nltk
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
import csv

data = pd.read_csv('iseardataset.csv')
test_data = data

stemmer = SnowballStemmer('english')
words = stopwords.words("english")

data['cleaned'] = data['text'].apply(lambda x: " ".join([stemmer.stem(i) for i in re.sub("[^a-zA-Z]", " ", x).split() if i not in words]).lower())
test_data['cleaned'] = data['text'].apply(lambda x: " ".join([stemmer.stem(i) for i in re.sub("[^a-zA-Z]", " ", x).split() if i not in words]).lower())

data['cleaned'][1]

'everi time i imagin someon i love i could contact serious ill even death'

In [13]:
import numpy as np
wordsList = np.load('wordsList.npy')
print('Loaded the word list!')
wordsList = wordsList.tolist() #Originally loaded as numpy array
wordsList = [word.decode('UTF-8') for word in wordsList] #Encode words as UTF-8
SeqLength = 42
counter = 0
for p in wordsList:
    counter = counter+1
    if counter >= SeqLength:                
        break
        
wordVectors = np.load('wordVectors.npy')
wordVectors[21]

Loaded the word list!


array([ 0.35215 , -0.35603 ,  0.25708 , -0.10611 , -0.20718 ,  0.63596 ,
       -1.0129  , -0.45964 , -0.48749 , -0.080555,  0.43769 ,  0.46046 ,
       -0.80943 , -0.23336 ,  0.46623 , -0.10866 , -0.1221  , -0.63544 ,
       -0.73486 , -0.24848 ,  0.4317  ,  0.092264,  0.52033 , -0.46784 ,
        0.016798, -1.5124  , -0.19986 , -0.43351 , -0.59247 ,  0.18088 ,
        3.5194  , -0.7024  ,  0.23613 , -0.68514 , -0.37009 , -0.080451,
        0.10635 , -0.085495, -0.18451 ,  0.29771 ,  0.18123 ,  0.53627 ,
       -0.1001  , -0.55165 ,  0.098833, -0.12942 , -0.82628 , -0.4329  ,
       -0.10301 , -0.56079 ], dtype=float32)

In [14]:
labeltext = data['label']

labeltext1= data['label']


testdata = data['cleaned']

In [15]:
uniqueLabel=[]
for w in labeltext:
    if w not in uniqueLabel:
        uniqueLabel.append(w)
        
uniqueLabel

['joy', 'fear', 'anger', 'sadness', 'disgust', 'shame', 'guilt']

In [16]:
counter=[]
for word in uniqueLabel:
    count=0
    for word1 in labeltext:
        if word==word1:
            count=count+1
    counter.append(count)
    
sum(counter)

7516

In [17]:
list1 = data['cleaned']


len(list1)


list1[0]

'on day i feel close partner friend when i feel peac also experi close contact peopl i regard great'

In [18]:
numWords=[]
x = []
for pf in list1:
    counter = len(pf.split())
    x.append(counter)
    numWords.append(counter)

numFiles = len(numWords)
print('The total number of files is', numFiles)
print('The total number of words in the files is', sum(numWords))
print('The average number of words in the files is', sum(numWords)/len(numWords))

The total number of files is 7516
The total number of words in the files is 91532
The average number of words in the files is 12.178286322511974


In [19]:
maxSeqLength = 24

In [20]:
import tensorflow as tf
sess = tf.Session()

In [21]:
import re
strip_special_chars = re.compile("[^A-Za-z0-9 ]+")

def cleanSentences(string):
    string = string.lower().replace("<br />", " ")
    return re.sub(strip_special_chars, "", string.lower())

In [88]:
# ids = np.zeros((numFiles, maxSeqLength), dtype='int32')
# fileCounter = 0
# for pf in list1:
#     indexCounter = 0
#     cleanedLine = cleanSentences(pf)
#     split = cleanedLine.split()
#     for word in split:
#         try:
#             ids[fileCounter][indexCounter] = wordsList.index(word)
#         except ValueError:
#             ids[fileCounter][indexCounter] = 399999 #Vector for unkown words
#         indexCounter = indexCounter + 1
#         if indexCounter >= maxSeqLength:
#             break
#     fileCounter = fileCounter + 1 
    
# np.save('idsMatrixQ1', ids)

In [89]:
# ids = np.zeros((numFiles, maxSeqLength), dtype='int32')
# fileCounter = 0
# for pf in testdata:
#     indexCounter = 0
#     cleanedLine = cleanSentences(pf)
#     split = cleanedLine.split()
#     for word in split:
#         try:
#             ids[fileCounter][indexCounter] = wordsList.index(word)
#         except ValueError:
#             ids[fileCounter][indexCounter] = 399999 #Vector for unkown words
#         indexCounter = indexCounter + 1
#         if indexCounter >= maxSeqLength:
#             break
#     fileCounter = fileCounter + 1 
    
# np.save('idsMatrixQ2', ids)

In [22]:
ids1 = np.load('idsMatrixQ1.npy')


ids1[41]


ids = np.load('idsMatrixQ2.npy')
ids[0]

ids[41]

array([    61,     41,    998,   6710, 399999,     41,  90634,    530,
           41,   2716, 399999,  86821,   1927,   1671,     79, 399999,
        11056,      0,      0,      0,      0,      0,      0,      0])

In [23]:
from random import randint

def getTrainBatch():
    labels = []
    arr = np.zeros([batchSize, maxSeqLength])
    for i in range(batchSize):
        num = randint(1,7515)
        labeltxt = labeltext[num]
        if labeltxt=="joy":
            labels.append([1,0,0,0,0,0,0])
        if labeltxt=="fear":
            labels.append([0,1,0,0,0,0,0])
        if labeltxt=="anger":
            labels.append([0,0,1,0,0,0,0])
        if labeltxt=="sadness":
            labels.append([0,0,0,1,0,0,0])
        if labeltxt=="disgust":
            labels.append([0,0,0,0,1,0,0])
        if labeltxt=="shame":
            labels.append([0,0,0,0,0,1,0])
        if labeltxt=="guilt":
            labels.append([0,0,0,0,0,0,1])
        arr[i] = ids[num-1:num]
    return arr, labels

def getTestBatch():
    labels = []
    arr = np.zeros([batchSize, maxSeqLength])
    for i in range(batchSize):
        num = randint(1,7515)
        labeltxt = labeltext1[num]
        if labeltxt=="joy":
            labels.append([1,0,0,0,0,0,0])
        if labeltxt=="fear":
            labels.append([0,1,0,0,0,0,0])
        if labeltxt=="anger":
            labels.append([0,0,1,0,0,0,0])
        if labeltxt=="sadness":
            labels.append([0,0,0,1,0,0,0])
        if labeltxt=="disgust":
            labels.append([0,0,0,0,1,0,0])
        if labeltxt=="shame":
            labels.append([0,0,0,0,0,1,0])
        if labeltxt=="guilt":
            labels.append([0,0,0,0,0,0,1])
        arr[i] = ids1[num-1:num]
    return arr, labels

In [24]:
batchSize = 64
lstmUnits = 10
numClasses = 7
iterations = 100000
numDimensions = 300

In [25]:
import tensorflow as tf
tf.reset_default_graph()

labels = tf.placeholder(tf.float32, [batchSize, numClasses])
input_data = tf.placeholder(tf.int32, [batchSize, maxSeqLength])

In [26]:
data = tf.Variable(tf.zeros([batchSize, maxSeqLength, numDimensions]),dtype=tf.float32)
data = tf.nn.embedding_lookup(wordVectors,input_data)
data.shape

TensorShape([Dimension(64), Dimension(24), Dimension(50)])

In [27]:
lstmCell = tf.contrib.rnn.BasicLSTMCell(lstmUnits)
lstmCell = tf.contrib.rnn.DropoutWrapper(cell=lstmCell, output_keep_prob=0.75)
value, _ = tf.nn.dynamic_rnn(lstmCell, data, dtype=tf.float32)

weight = tf.Variable(tf.truncated_normal([lstmUnits, numClasses]))
bias = tf.Variable(tf.constant(0.1, shape=[numClasses]))
value = tf.transpose(value, [1, 0, 2])
last = tf.gather(value, int(value.get_shape()[0]) - 1)
prediction = (tf.matmul(last, weight) + bias)
print(prediction)

correctPred = tf.equal(tf.argmax(prediction,1), tf.argmax(labels,1))
print(correctPred)
accuracy = tf.reduce_mean(tf.cast(correctPred, tf.float32))
print(accuracy)

loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=prediction, labels=labels))
optimizer = tf.train.AdamOptimizer().minimize(loss)

Tensor("add:0", shape=(64, 7), dtype=float32)
Tensor("Equal:0", shape=(64,), dtype=bool)
Tensor("Mean:0", shape=(), dtype=float32)
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.



In [28]:
import datetime

tf.summary.scalar('Loss', loss)
tf.summary.scalar('Accuracy', accuracy)
merged = tf.summary.merge_all()
logdir = "tensorboard/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S") + "/"
writer = tf.summary.FileWriter(logdir, sess.graph)

In [29]:
# sess = tf.InteractiveSession()
# saver = tf.train.Saver()
# sess.run(tf.global_variables_initializer())

# for i in range(iterations):
#    #Next Batch of reviews
#    nextBatch, nextBatchLabels = getTrainBatch()
#    sess.run(optimizer, {input_data: nextBatch, labels: nextBatchLabels})
   
#    #Write summary to Tensorboard
#    if (i % 50 == 0):
#        summary = sess.run(merged, {input_data: nextBatch, labels: nextBatchLabels})
#        writer.add_summary(summary, i)

#    #Save the network every 10,000 training iterations
#    if (i % 10000 == 0 and i != 0):
#        save_path = saver.save(sess, "models1/pretrained_lstm.ckpt", global_step=i)
#        print("saved to %s" % save_path)
# writer.close()

In [30]:
sess = tf.InteractiveSession()
saver = tf.train.Saver()
saver.restore(sess, tf.train.latest_checkpoint('models1'))

INFO:tensorflow:Restoring parameters from models1\pretrained_lstm.ckpt-90000


In [31]:
iterations = 50
for i in range(iterations):
    nextBatch, nextBatchLabels = getTestBatch();
    print("Accuracy for this batch:", (sess.run(accuracy, {input_data: nextBatch, labels: nextBatchLabels})) * 100)

Accuracy for this batch: 60.9375
Accuracy for this batch: 70.3125
Accuracy for this batch: 46.875
Accuracy for this batch: 54.6875
Accuracy for this batch: 60.9375
Accuracy for this batch: 57.8125
Accuracy for this batch: 53.125
Accuracy for this batch: 59.375
Accuracy for this batch: 56.25
Accuracy for this batch: 67.1875
Accuracy for this batch: 50.0
Accuracy for this batch: 56.25
Accuracy for this batch: 56.25
Accuracy for this batch: 54.6875
Accuracy for this batch: 67.1875
Accuracy for this batch: 70.3125
Accuracy for this batch: 59.375
Accuracy for this batch: 65.625
Accuracy for this batch: 65.625
Accuracy for this batch: 62.5
Accuracy for this batch: 59.375
Accuracy for this batch: 57.8125
Accuracy for this batch: 50.0
Accuracy for this batch: 59.375
Accuracy for this batch: 59.375
Accuracy for this batch: 57.8125
Accuracy for this batch: 62.5
Accuracy for this batch: 59.375
Accuracy for this batch: 53.125
Accuracy for this batch: 53.125
Accuracy for this batch: 64.0625
Accurac

In [51]:
import re
strip_special_chars = re.compile("[^A-Za-z0-9 ]+")

def cleanSentences(string):
    string = string.lower().replace("<br />", " ")
    return re.sub(strip_special_chars, "", string.lower())

def getSentenceMatrix(sentence):
    arr = np.zeros([batchSize, maxSeqLength])
    sentenceMatrix = np.zeros([batchSize,maxSeqLength], dtype='int32')
    cleanedSentence = cleanSentences(sentence)
    split = cleanedSentence.split()
    for indexCounter,word in enumerate(split):
        try:
            sentenceMatrix[0,indexCounter] = wordsList.index(word)
        except ValueError:
            sentenceMatrix[0,indexCounter] = 399999 #Vector for unkown words
    return sentenceMatrix

In [33]:
inputText = "When I was not accepted as a student in finance and accounting."
inputMatrix = getSentenceMatrix(inputText)

In [34]:
predictedSentiment = sess.run(prediction, {input_data: inputMatrix})[0]
max1 = 0
count = 0
for i in range(0,6):
    if predictedSentiment[max1] < predictedSentiment[i]:
        max1 = i
        count = predictedSentiment[i]

print(max1,count)
print(uniqueLabel[max1])
predictedSentiment

1 1.8039901
fear


array([-0.06949106,  1.8039901 , -0.872873  ,  0.00306439,  0.49031854,
       -0.20453809, -0.3636682 ], dtype=float32)

In [35]:
inputText = "When one lets friends down"
inputMatrix = getSentenceMatrix(inputText)

In [36]:
predictedSentiment = sess.run(prediction, {input_data: inputMatrix})[0]
max1 = 0
count = 0
for i in range(0,6):
    if predictedSentiment[max1] < predictedSentiment[i]:
        max1 = i
        count = predictedSentiment[i]

print(max1,count)
print(uniqueLabel[max1])
predictedSentiment

3 0.57973254
sadness


array([ 0.17515756, -0.5884043 , -0.58662677,  0.57973254,  0.43536714,
        0.01479686, -0.09924237], dtype=float32)

In [37]:
inputText = "When the whole family gets together for a one week holiday."
inputMatrix = getSentenceMatrix(inputText)

In [38]:
predictedSentiment = sess.run(prediction, {input_data: inputMatrix})[0]
max1 = 0
count = 0
for i in range(0,6):
    if predictedSentiment[max1] < predictedSentiment[i]:
        max1 = i
        count = predictedSentiment[i]

print(max1,count)
print(uniqueLabel[max1])
predictedSentiment

1 0.9272617
fear


array([ 0.60364896,  0.9272617 , -1.0228194 , -0.370823  ,  0.7914897 ,
       -1.3466926 ,  0.191217  ], dtype=float32)

In [49]:
inputText = "On days when I feel close to my partner and other friends. When I feel at peace with myself and also experience a close contact with people whom I regard greatly."
inputMatrix = getSentenceMatrix(inputText)

In [50]:
inputArray = pd.read_csv('iseardataset.csv')
inputTextArray = inputArray["text"]
inputLength = len(inputTextArray)
i=0
for text in inputTextArray:
    inputText = text
    print(text)
    inputMatrix = getSentenceMatrix(inputText)
    i=i+1
    predictedSentiment = sess.run(prediction, {input_data: inputMatrix})[0]
    max1 = 0
    count = 0
    for j in range(0,6):
        if predictedSentiment[max1] < predictedSentiment[j]:
            max1 = j
            count = predictedSentiment[j]
    predictedArray[i] = uniqueLabel[max1]
    if(i>=inputLength):
        break

On days when I feel close to my partner and other friends.   
When I feel at peace with myself and also experience a close  
contact with people whom I regard greatly.


ValueError: Cannot feed value of shape (64, 80) for Tensor 'Placeholder_1:0', which has shape '(64, 24)'

In [42]:
len(inputTextArray)

7516

In [6]:
# Necessary imports: 
from sklearn.metrics import precision_recall_fscore_support
import numpy as np

In [10]:
y_true = np.array(['cat', 'dog', 'pig', 'cat', 'dog', 'pig'])
y_pred = np.array(['cat', 'pig', 'dog', 'cat', 'cat', 'dog'])
print(precision_recall_fscore_support(y_true, y_pred, average='macro'))

(0.2222222222222222, 0.3333333333333333, 0.26666666666666666, None)
